# Generated by Django 5.0.6 on 2024-06-28 19:21

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_content_aboutuspage_intro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuspage',
            old_name='content',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='courses',
            field=wagtail.fields.StreamField([('course', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True),
        ),
    ]
